name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare NuGet.Config
      uses: datamonsters/replace-action@v2
      with:
        files: 'NuGet.Config.actions'
        replacements: '%%username%%=xivk,%%token%%=${{ secrets.PACKAGES_SECRET }}'
    - run: mv NuGet.Config.actions NuGet.Config 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Publish project
      run: dotnet publish -c release
      working-directory: ./src/BikeDataProject.API/
    - name: Login to GitHub Packages with Docker
      run: docker login https://docker.pkg.github.com -u xivk -p ${{ secrets.PACKAGES_SECRET }}
    - name: Tag the Docker image
      run: docker tag geo-api:1.0 docker.pkg.github.com/bikedataproject/geo-api/geo-api:1.0
      working-directory: ./src/BikeDataProject.API/
    - name: Build the Docker image for the package
      run: docker build -t docker.pkg.github.com/bikedataproject/geo-api/geo-api:1.0 .
      working-directory: ./src/BikeDataProject.API/
    - name: Publish the image to GitHub packages.
      run: docker push docker.pkg.github.com/bikedataproject/geo-api/geo-api:1.0
      working-directory: ./src/BikeDataProject.API/
